{{- if .Values.persistentVolumes.create -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mongodb-pv-claim
spec:
  {{- if .Values.persistentVolumes.enableStorageClass }}
  storageClassName: {{ .Release.Name }}-{{ .Values.persistentVolumes.storageClasses.mongo }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
{{- if .Values.persistentVolumes.enableStorageClass }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-mongodb-pv-volume
  labels:
    type: local
spec:
  storageClassName: {{ .Release.Name }}-{{ .Values.persistentVolumes.storageClasses.mongo }}
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/{{ .Release.Name }}-mongodb-data"
{{- end }}
{{- end }}