{{- if .Values.networkPolicies.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-server-mysql
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-server
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-mysql
    ports:
    - port: 3306

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-mysql-server
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-mysql
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: {{ .Release.Name }}-server
      ports:
      - port: 3306
{{- end }}