{{- if .Values.networkPolicies.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-topo-mongodb
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-toposervice
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-mongodb
    ports:
    - protocol: TCP
      port: 27017
      endPort: 27019

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-mongodb-topo
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-mongodb
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: {{ .Release.Name }}-toposervice
      ports:
      - protocol: TCP
        port: 27017
        endPort: 27019
{{- end }}