---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-planner-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-planner
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-planner
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 1001
      containers:
      - name: {{ .Release.Name }}-planner
        image: {{ .Values.services.planner.image }}:{{ .Values.services.planner.tag }}
        env:
        - name: TOPO_HOST
          value: {{ .Release.Name }}-toposervice-service
        - name: TOPO_PORT
          value: "8181"
        - name: GRPC_CLIENT_WEATHERSERVER_ADDRESS
          value: static://{{ .Release.Name }}-weatherservice-service:9090
        - name: SPRING_CLOUD_STREAM_RABBIT_BINDER_NODES
          value: {{ .Release.Name }}-rabbitmq-service:5672
        - name: SPRING_RABBITMQ_HOST
          value: {{ .Release.Name }}-rabbitmq-service
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          value: root
        - name: SPRING_RABBITMQ_PASSWORD
          value: password
