---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-rabbitmq-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-rabbitmq
    spec:
      containers:
      - name: {{ .Release.Name }}-rabbitmq
        image: {{ .Values.services.rabbitmq.image }}:{{ .Values.services.rabbitmq.tag }}
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: root
        - name: RABBITMQ_DEFAULT_PASS
          value: password
        ports:
        - containerPort: 5672
        - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rabbitmq-service
  labels:
    app: {{ .Release.Name }}-rabbitmq
spec:
  ports:
  - port: 5672
    targetPort: 5672
    protocol: TCP
    name: {{ .Release.Name }}-rabbitmq-port-5672
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: {{ .Release.Name }}-rabbitmq-port-15672
  selector:
    app: {{ .Release.Name }}-rabbitmq
  type: ClusterIP
