apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secret
  namespace: mca-app
type: Opaque
data:
  # generate 8 chars long random string, base64 encode it and then double-quote the result string.
  username: {{ .Values.services.mysql.username }}
{{- if .Values.services.mysql.password }}
  password: {{ .Values.services.mysql.password | b64enc | quote }}
{{- else }}
  password: {{ randAlphaNum 8 | b64enc | quote }}
{{- end }}
