---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongodb-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongodb
    spec:
      
      containers:
      - name: {{ .Release.Name }}-mongodb
        image: {{ .Values.services.mongodb.image }}:{{ .Values.services.mongodb.tag }}
        env:
        - name: MONGO_INITDB_DATABASE
          value: topoDB
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 27017
        - containerPort: 27018
        - containerPort: 27019
        volumeMounts:
        - name: {{ .Release.Name }}-mongodb-persistent-storage
          mountPath: /data/db
      volumes:
      - name: {{ .Release.Name }}-mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-mongodb-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb-service
  labels:
    app: {{ .Release.Name }}-mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: {{ .Release.Name }}-mongodb-port-27017
  - port: 27018
    targetPort: 27018
    protocol: TCP
    name: {{ .Release.Name }}-mongodb-port-27018
  - port: 27019
    targetPort: 27019
    protocol: TCP
    name: {{ .Release.Name }}-mongodb-port-27019
  selector:
    app: {{ .Release.Name }}-mongodb
  type: ClusterIP
