{{- if .Values.networkPolicies.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-planner-rabbitmq
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-planner
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-rabbitmq
    ports:
    - port: 5672
      protocol: TCP
    - port: 15672
      protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-rabbitmq-planner
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-rabbitmq
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: {{ .Release.Name }}-planner
      ports:
      - port: 5672
        protocol: TCP
      - port: 15672
        protocol: TCP
{{- end }}