---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: mca-app
  labels:
    app: mongo
    type: local
spec:
  storageClassName: mongodb
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/db/mongo"
  capacity:
    storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: mca-app
  labels:
    app: mongo
spec:
  storageClassName: mongodb
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: mca-app
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:4.2.3
        ports:
          - containerPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
---
apiVersion: v1 
kind: Service
metadata:
  name: mongo
  namespace: mca-app
  labels:
    app: mongo
spec:
  ports:
  - name: mongo-port
    protocol: TCP
    port: 27017
    targetPort: 27017
  selector:
    app: mongo
  type: ClusterIP