---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: mca-app
  labels:
    app: mysql
    type: local
spec:
  storageClassName: mysql
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/db/mysql"
  capacity:
    storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: mca-app
  labels:
    app: mysql
spec:
  storageClassName: mysql
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: mca-app
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8
        ports:
          - containerPort: 3306
        env: 
        - name: MYSQL_DATABASE
          value: database
        - name: MYSQL_USER
          value: myuser
        - name: MYSQL_PASSWORD
          value:  mypassword
        - name: MYSQL_ROOT_PASSWORD
          value: mypassword
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1 
kind: Service
metadata:
  name: mysql
  namespace: mca-app
  labels:
    app: mysql
spec:
  ports:
  - name: sql
    protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP