apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
 # namespace: mca-app
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: fjvela/urjc-fjvela-rabbitmq:1.0.0
        ports:
          - containerPort: 5672
---
apiVersion: v1 
kind: Service
metadata:
  name: rabbitmq
 # namespace: mca-app
  labels:
    app: rabbitmq
spec:
  ports:
  - name: rabbitmq-port
    protocol: TCP
    port: 5672
    targetPort: 5672
  selector:
    app: rabbitmq
  type: ClusterIP
