apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: mca-app
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      securityContext:
        runAsUser: 1001
      containers:
      - name: server
        image: fjvela/urjc-fjvela-server:1.0.5
        ports:
          - containerPort: 8080
        env:
        - name: RABBITMQ_SERVER
          value: rabbitmq
        - name: MONGO_SERVER
          value: mongo
        - name: MONGO_DATABASE
          value: database
        securityContext:
          allowPrivilegeEscalation: false  
---
apiVersion: v1 
kind: Service
metadata:
  name: server  
  namespace: mca-app
  labels:
    app: server
spec:
  ports:
  - name: server
    protocol: TCP
    port: 8080
  selector:
    app: server
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: multi-ingress
 namespace: mca-app
 annotations:
   nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
 rules:
 - host: cluster-ip
   http:
     paths:
     - path: /(.*)
       pathType: ImplementationSpecific
       backend:
         service:
           name: server
           port:
             number: 8080
  
