apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment  
 # namespace: mca-app
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      securityContext:
        runAsUser: 1001
      containers:
      - name: worker
        image: fjvela/urjc-fjvela-worker:1.0.1
        env:
        - name: RABBITMQ_SERVER
          value: rabbitmq
        - name: UPPERCASE_GRPC_SERVER
          value: static://external-service:9090
        - name: MYSQL_SERVER
          value: mysql
        - name: MYSQL_DATABASE
          value: database
        - name: MYSQL_USER
          value: myuser
        - name: MYSQL_PASSWORD
          value: mypassword
        securityContext:
            allowPrivilegeEscalation: false
