{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
   - host: {{ .Values.ingress.host }}
     http:
      paths:
      - path: /toposervice/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-toposervice-service
            port:
              number: 8181
      - path: /(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-server-service
            port:
              number: 3000
{{- end }}      