{{- if .Values.networkPolicies.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-planner-weather
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-planner
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-weatherservice
    ports:
    - port: 9090

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-weather-planner
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-weatherservice
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: {{ .Release.Name }}-planner
      ports:
      - port: 9090
{{- end }}       