{{- if .Values.networkPolicies.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-server-external-ingress
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-server
  ingress:
    - from: []
      ports:
      - protocol: TCP
        port: 3000
{{- end }}