ingress:
  enabled: true
  host: "cluster-ip"
  serviceType: LoadBalancer

persistentVolumes:
  create: true
  enableStorageClass: true
  storageClasses:
    mysql: mysql
    mongo: mongodb
    rabbit: rabbitmq

networkPolicies:
  enabled: false

services:
  mongodb:
    image: mongo
    tag: "4.2.3"
  mysql:
    image: mysql
    tag: "8.0.28"
    password: "mypassword"
  rabbitmq:
    image: fjvela/urjc-fjvela-rabbitmq
    tag: "1.0.0"
  server:
    image: fjvela/urjc-fjvela-server
    tag: "1.0.5"
  worker:
    image: fjvela/urjc-fjvela-worker
    tag: "1.0.1"
  external:
    image: fjvela/urjc-fjvela-external-service
    tag: "1.0.1"
